### ISSUE TITLE
请问作者，您的publickey和privetekey是如何生成的？

### ISSUE THREAD

**Issue by Frederic-Zhou** [suihaohao/encrypt-and-decode-of-golang-and-node#1]
我在本地使用openssl 生成的 prikey和pubkey 无法实现实现 解密。会报错
但是用仓库的实例就能正确的解密。
请问作者你生成privatekey.pem和publickey.pem的

**Comment by suihaohao** [comment]
pem有pkcs1和pkcs8的区别吗，你可以用pkcs1试一下加解密。

**Comment by suihaohao** [comment]
pem有pkcs1和pkcs8的区别吗，你可以用pkcs1试一下加解密。

**Comment by Frederic-Zhou** [comment]
谢谢！已经成功了。
我使用本地的openssl生成的key无法成功，后来下载Aliyun的生成工具就成功了

可能是我本地的openssl的版本问题吧。
